// Autogenerated from Pigeon (v26.1.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsGemmaApi(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsGemmaApi(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsGemmaApi(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashGemmaApi(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashGemmaApi(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashGemmaApi(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

/// Statistics from model generation
///
/// Generated class from Pigeon that represents data sent in messages.
struct GenerationStats: Hashable {
  var generatedTokens: Int64
  var inferenceEndMs: Int64
  var promptEvalEndMs: Int64
  var tokensPerSecond: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> GenerationStats? {
    let generatedTokens = pigeonVar_list[0] as! Int64
    let inferenceEndMs = pigeonVar_list[1] as! Int64
    let promptEvalEndMs = pigeonVar_list[2] as! Int64
    let tokensPerSecond = pigeonVar_list[3] as! Double

    return GenerationStats(
      generatedTokens: generatedTokens,
      inferenceEndMs: inferenceEndMs,
      promptEvalEndMs: promptEvalEndMs,
      tokensPerSecond: tokensPerSecond
    )
  }
  func toList() -> [Any?] {
    return [
      generatedTokens,
      inferenceEndMs,
      promptEvalEndMs,
      tokensPerSecond,
    ]
  }
  static func == (lhs: GenerationStats, rhs: GenerationStats) -> Bool {
    return deepEqualsGemmaApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashGemmaApi(value: toList(), hasher: &hasher)
  }
}

/// Configuration for model loading
///
/// Generated class from Pigeon that represents data sent in messages.
struct ModelConfig: Hashable {
  var modelPath: String
  var tokenizerPath: String
  var temperature: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ModelConfig? {
    let modelPath = pigeonVar_list[0] as! String
    let tokenizerPath = pigeonVar_list[1] as! String
    let temperature = pigeonVar_list[2] as! Double

    return ModelConfig(
      modelPath: modelPath,
      tokenizerPath: tokenizerPath,
      temperature: temperature
    )
  }
  func toList() -> [Any?] {
    return [
      modelPath,
      tokenizerPath,
      temperature,
    ]
  }
  static func == (lhs: ModelConfig, rhs: ModelConfig) -> Bool {
    return deepEqualsGemmaApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashGemmaApi(value: toList(), hasher: &hasher)
  }
}

private class GemmaApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return GenerationStats.fromList(self.readValue() as! [Any?])
    case 130:
      return ModelConfig.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class GemmaApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? GenerationStats {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? ModelConfig {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class GemmaApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return GemmaApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return GemmaApiPigeonCodecWriter(data: data)
  }
}

class GemmaApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = GemmaApiPigeonCodec(readerWriter: GemmaApiPigeonCodecReaderWriter())
}


/// Main API for Gemma inference
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol GemmaApi {
  /// Load the model with given configuration
  /// Returns 0 on success, error code otherwise
  func loadModel(config: ModelConfig, completion: @escaping (Result<Int64, Error>) -> Void)
  /// Generate text from prompt
  /// Returns generated text
  func generate(prompt: String, maxTokens: Int64, completion: @escaping (Result<String, Error>) -> Void)
  /// Stop current generation
  func stopGeneration() throws
  /// Unload the model and free resources
  func unloadModel() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class GemmaApiSetup {
  static var codec: FlutterStandardMessageCodec { GemmaApiPigeonCodec.shared }
  /// Sets up an instance of `GemmaApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: GemmaApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Load the model with given configuration
    /// Returns 0 on success, error code otherwise
    let loadModelChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.twyns.GemmaApi.loadModel\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      loadModelChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let configArg = args[0] as! ModelConfig
        api.loadModel(config: configArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      loadModelChannel.setMessageHandler(nil)
    }
    /// Generate text from prompt
    /// Returns generated text
    let generateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.twyns.GemmaApi.generate\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      generateChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let promptArg = args[0] as! String
        let maxTokensArg = args[1] as! Int64
        api.generate(prompt: promptArg, maxTokens: maxTokensArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      generateChannel.setMessageHandler(nil)
    }
    /// Stop current generation
    let stopGenerationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.twyns.GemmaApi.stopGeneration\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopGenerationChannel.setMessageHandler { _, reply in
        do {
          try api.stopGeneration()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopGenerationChannel.setMessageHandler(nil)
    }
    /// Unload the model and free resources
    let unloadModelChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.twyns.GemmaApi.unloadModel\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      unloadModelChannel.setMessageHandler { _, reply in
        do {
          try api.unloadModel()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      unloadModelChannel.setMessageHandler(nil)
    }
  }
}
/// Callback from native to Flutter for streaming results
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol GemmaCallbackProtocol {
  /// Called when a new token is generated
  func onToken(token tokenArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// Called when generation is complete with stats
  func onComplete(stats statsArg: GenerationStats, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// Called when an error occurs
  func onError(error errorArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class GemmaCallback: GemmaCallbackProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: GemmaApiPigeonCodec {
    return GemmaApiPigeonCodec.shared
  }
  /// Called when a new token is generated
  func onToken(token tokenArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.twyns.GemmaCallback.onToken\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([tokenArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  /// Called when generation is complete with stats
  func onComplete(stats statsArg: GenerationStats, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.twyns.GemmaCallback.onComplete\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([statsArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  /// Called when an error occurs
  func onError(error errorArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.twyns.GemmaCallback.onError\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([errorArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
