// Autogenerated from Pigeon (v17.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

/// Configuration for model loading
class ModelConfig {
  ModelConfig({
    this.modelPath,
    this.tokenizerPath,
    this.specialTokens,
  });

  String? modelPath;

  String? tokenizerPath;

  List<String?>? specialTokens;

  Object encode() {
    return <Object?>[
      modelPath,
      tokenizerPath,
      specialTokens,
    ];
  }

  static ModelConfig decode(Object result) {
    result as List<Object?>;
    return ModelConfig(
      modelPath: result[0] as String?,
      tokenizerPath: result[1] as String?,
      specialTokens: (result[2] as List<Object?>?)?.cast<String?>(),
    );
  }
}

/// Configuration for text generation
class GenerationConfig {
  GenerationConfig({
    this.sequenceLength,
    this.maximumNewTokens,
    this.temperature,
    this.topP,
  });

  int? sequenceLength;

  int? maximumNewTokens;

  double? temperature;

  double? topP;

  Object encode() {
    return <Object?>[
      sequenceLength,
      maximumNewTokens,
      temperature,
      topP,
    ];
  }

  static GenerationConfig decode(Object result) {
    result as List<Object?>;
    return GenerationConfig(
      sequenceLength: result[0] as int?,
      maximumNewTokens: result[1] as int?,
      temperature: result[2] as double?,
      topP: result[3] as double?,
    );
  }
}

/// Response from model operations
class ModelResponse {
  ModelResponse({
    this.success,
    this.error,
    this.message,
    this.loadTime,
  });

  bool? success;

  String? error;

  String? message;

  double? loadTime;

  Object encode() {
    return <Object?>[
      success,
      error,
      message,
      loadTime,
    ];
  }

  static ModelResponse decode(Object result) {
    result as List<Object?>;
    return ModelResponse(
      success: result[0] as bool?,
      error: result[1] as String?,
      message: result[2] as String?,
      loadTime: result[3] as double?,
    );
  }
}

/// Token generation callback data
class TokenData {
  TokenData({
    this.token,
    this.tokenCount,
    this.tokensPerSecond,
  });

  String? token;

  int? tokenCount;

  double? tokensPerSecond;

  Object encode() {
    return <Object?>[
      token,
      tokenCount,
      tokensPerSecond,
    ];
  }

  static TokenData decode(Object result) {
    result as List<Object?>;
    return TokenData(
      token: result[0] as String?,
      tokenCount: result[1] as int?,
      tokensPerSecond: result[2] as double?,
    );
  }
}

/// Memory usage information
class MemoryInfo {
  MemoryInfo({
    this.usedMemoryMB,
    this.availableMemoryMB,
  });

  int? usedMemoryMB;

  int? availableMemoryMB;

  Object encode() {
    return <Object?>[
      usedMemoryMB,
      availableMemoryMB,
    ];
  }

  static MemoryInfo decode(Object result) {
    result as List<Object?>;
    return MemoryInfo(
      usedMemoryMB: result[0] as int?,
      availableMemoryMB: result[1] as int?,
    );
  }
}

class _ExecutorchApiCodec extends StandardMessageCodec {
  const _ExecutorchApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is GenerationConfig) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else if (value is MemoryInfo) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is ModelConfig) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is ModelResponse) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128: 
        return GenerationConfig.decode(readValue(buffer)!);
      case 129: 
        return MemoryInfo.decode(readValue(buffer)!);
      case 130: 
        return ModelConfig.decode(readValue(buffer)!);
      case 131: 
        return ModelResponse.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Platform interface for ExecuTorch operations
class ExecutorchApi {
  /// Constructor for [ExecutorchApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  ExecutorchApi({BinaryMessenger? binaryMessenger})
      : __pigeon_binaryMessenger = binaryMessenger;
  final BinaryMessenger? __pigeon_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _ExecutorchApiCodec();

  /// Initialize the ExecuTorch runner with model and tokenizer
  Future<ModelResponse> loadModel(ModelConfig config) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.executorch_bridge_flutter.ExecutorchApi.loadModel';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[config]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as ModelResponse?)!;
    }
  }

  /// Check if model is currently loaded
  Future<bool> isModelLoaded() async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.executorch_bridge_flutter.ExecutorchApi.isModelLoaded';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(null) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as bool?)!;
    }
  }

  /// Unload the current model
  Future<void> unloadModel() async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.executorch_bridge_flutter.ExecutorchApi.unloadModel';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(null) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Generate text from prompt
  Future<ModelResponse> generateText(String prompt, GenerationConfig config) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.executorch_bridge_flutter.ExecutorchApi.generateText';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[prompt, config]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as ModelResponse?)!;
    }
  }

  /// Stop ongoing text generation
  Future<void> stopGeneration() async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.executorch_bridge_flutter.ExecutorchApi.stopGeneration';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(null) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Get current memory usage
  Future<MemoryInfo> getMemoryInfo() async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.executorch_bridge_flutter.ExecutorchApi.getMemoryInfo';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(null) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as MemoryInfo?)!;
    }
  }

  /// Validate if file exists at path
  Future<bool> validateFilePath(String path) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.executorch_bridge_flutter.ExecutorchApi.validateFilePath';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[path]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as bool?)!;
    }
  }
}

class _ExecutorchFlutterApiCodec extends StandardMessageCodec {
  const _ExecutorchFlutterApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is TokenData) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128: 
        return TokenData.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Flutter interface for receiving callbacks from platform
abstract class ExecutorchFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _ExecutorchFlutterApiCodec();

  /// Called when a new token is generated
  void onTokenGenerated(TokenData token);

  /// Called when generation is complete
  void onGenerationComplete(String fullText, int totalTokens);

  /// Called when an error occurs
  void onError(String error);

  static void setup(ExecutorchFlutterApi? api, {BinaryMessenger? binaryMessenger}) {
    {
      final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.executorch_bridge_flutter.ExecutorchFlutterApi.onTokenGenerated', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        __pigeon_channel.setMessageHandler(null);
      } else {
        __pigeon_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.executorch_bridge_flutter.ExecutorchFlutterApi.onTokenGenerated was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final TokenData? arg_token = (args[0] as TokenData?);
          assert(arg_token != null,
              'Argument for dev.flutter.pigeon.executorch_bridge_flutter.ExecutorchFlutterApi.onTokenGenerated was null, expected non-null TokenData.');
          try {
            api.onTokenGenerated(arg_token!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.executorch_bridge_flutter.ExecutorchFlutterApi.onGenerationComplete', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        __pigeon_channel.setMessageHandler(null);
      } else {
        __pigeon_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.executorch_bridge_flutter.ExecutorchFlutterApi.onGenerationComplete was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_fullText = (args[0] as String?);
          assert(arg_fullText != null,
              'Argument for dev.flutter.pigeon.executorch_bridge_flutter.ExecutorchFlutterApi.onGenerationComplete was null, expected non-null String.');
          final int? arg_totalTokens = (args[1] as int?);
          assert(arg_totalTokens != null,
              'Argument for dev.flutter.pigeon.executorch_bridge_flutter.ExecutorchFlutterApi.onGenerationComplete was null, expected non-null int.');
          try {
            api.onGenerationComplete(arg_fullText!, arg_totalTokens!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.executorch_bridge_flutter.ExecutorchFlutterApi.onError', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        __pigeon_channel.setMessageHandler(null);
      } else {
        __pigeon_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.executorch_bridge_flutter.ExecutorchFlutterApi.onError was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_error = (args[0] as String?);
          assert(arg_error != null,
              'Argument for dev.flutter.pigeon.executorch_bridge_flutter.ExecutorchFlutterApi.onError was null, expected non-null String.');
          try {
            api.onError(arg_error!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
