// Autogenerated from Pigeon (v17.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon


import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  if (exception is FlutterError) {
    return listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    return listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

private fun createConnectionError(channelName: String): FlutterError {
  return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/**
 * Configuration for model loading
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ModelConfig (
  val modelPath: String? = null,
  val tokenizerPath: String? = null,
  val specialTokens: List<String?>? = null

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): ModelConfig {
      val modelPath = list[0] as String?
      val tokenizerPath = list[1] as String?
      val specialTokens = list[2] as List<String?>?
      return ModelConfig(modelPath, tokenizerPath, specialTokens)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      modelPath,
      tokenizerPath,
      specialTokens,
    )
  }
}

/**
 * Configuration for text generation
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class GenerationConfig (
  val sequenceLength: Long? = null,
  val maximumNewTokens: Long? = null,
  val temperature: Double? = null,
  val topP: Double? = null

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): GenerationConfig {
      val sequenceLength = list[0].let { if (it is Int) it.toLong() else it as Long? }
      val maximumNewTokens = list[1].let { if (it is Int) it.toLong() else it as Long? }
      val temperature = list[2] as Double?
      val topP = list[3] as Double?
      return GenerationConfig(sequenceLength, maximumNewTokens, temperature, topP)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      sequenceLength,
      maximumNewTokens,
      temperature,
      topP,
    )
  }
}

/**
 * Response from model operations
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ModelResponse (
  val success: Boolean? = null,
  val error: String? = null,
  val message: String? = null,
  val loadTime: Double? = null

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): ModelResponse {
      val success = list[0] as Boolean?
      val error = list[1] as String?
      val message = list[2] as String?
      val loadTime = list[3] as Double?
      return ModelResponse(success, error, message, loadTime)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      success,
      error,
      message,
      loadTime,
    )
  }
}

/**
 * Token generation callback data
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class TokenData (
  val token: String? = null,
  val tokenCount: Long? = null,
  val tokensPerSecond: Double? = null

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): TokenData {
      val token = list[0] as String?
      val tokenCount = list[1].let { if (it is Int) it.toLong() else it as Long? }
      val tokensPerSecond = list[2] as Double?
      return TokenData(token, tokenCount, tokensPerSecond)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      token,
      tokenCount,
      tokensPerSecond,
    )
  }
}

/**
 * Memory usage information
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class MemoryInfo (
  val usedMemoryMB: Long? = null,
  val availableMemoryMB: Long? = null

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): MemoryInfo {
      val usedMemoryMB = list[0].let { if (it is Int) it.toLong() else it as Long? }
      val availableMemoryMB = list[1].let { if (it is Int) it.toLong() else it as Long? }
      return MemoryInfo(usedMemoryMB, availableMemoryMB)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      usedMemoryMB,
      availableMemoryMB,
    )
  }
}

@Suppress("UNCHECKED_CAST")
private object ExecutorchApiCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      128.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          GenerationConfig.fromList(it)
        }
      }
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MemoryInfo.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ModelConfig.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ModelResponse.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is GenerationConfig -> {
        stream.write(128)
        writeValue(stream, value.toList())
      }
      is MemoryInfo -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is ModelConfig -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is ModelResponse -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/**
 * Platform interface for ExecuTorch operations
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface ExecutorchApi {
  /** Initialize the ExecuTorch runner with model and tokenizer */
  fun loadModel(config: ModelConfig, callback: (Result<ModelResponse>) -> Unit)
  /** Check if model is currently loaded */
  fun isModelLoaded(): Boolean
  /** Unload the current model */
  fun unloadModel()
  /** Generate text from prompt */
  fun generateText(prompt: String, config: GenerationConfig, callback: (Result<ModelResponse>) -> Unit)
  /** Stop ongoing text generation */
  fun stopGeneration()
  /** Get current memory usage */
  fun getMemoryInfo(): MemoryInfo
  /** Validate if file exists at path */
  fun validateFilePath(path: String): Boolean

  companion object {
    /** The codec used by ExecutorchApi. */
    val codec: MessageCodec<Any?> by lazy {
      ExecutorchApiCodec
    }
    /** Sets up an instance of `ExecutorchApi` to handle messages through the `binaryMessenger`. */
    @Suppress("UNCHECKED_CAST")
    fun setUp(binaryMessenger: BinaryMessenger, api: ExecutorchApi?) {
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.executorch_bridge_flutter.ExecutorchApi.loadModel", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val configArg = args[0] as ModelConfig
            api.loadModel(configArg) { result: Result<ModelResponse> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.executorch_bridge_flutter.ExecutorchApi.isModelLoaded", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            var wrapped: List<Any?>
            try {
              wrapped = listOf<Any?>(api.isModelLoaded())
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.executorch_bridge_flutter.ExecutorchApi.unloadModel", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            var wrapped: List<Any?>
            try {
              api.unloadModel()
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.executorch_bridge_flutter.ExecutorchApi.generateText", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val promptArg = args[0] as String
            val configArg = args[1] as GenerationConfig
            api.generateText(promptArg, configArg) { result: Result<ModelResponse> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.executorch_bridge_flutter.ExecutorchApi.stopGeneration", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            var wrapped: List<Any?>
            try {
              api.stopGeneration()
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.executorch_bridge_flutter.ExecutorchApi.getMemoryInfo", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            var wrapped: List<Any?>
            try {
              wrapped = listOf<Any?>(api.getMemoryInfo())
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.executorch_bridge_flutter.ExecutorchApi.validateFilePath", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pathArg = args[0] as String
            var wrapped: List<Any?>
            try {
              wrapped = listOf<Any?>(api.validateFilePath(pathArg))
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
@Suppress("UNCHECKED_CAST")
private object ExecutorchFlutterApiCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      128.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          TokenData.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is TokenData -> {
        stream.write(128)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/**
 * Flutter interface for receiving callbacks from platform
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
@Suppress("UNCHECKED_CAST")
class ExecutorchFlutterApi(private val binaryMessenger: BinaryMessenger) {
  companion object {
    /** The codec used by ExecutorchFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      ExecutorchFlutterApiCodec
    }
  }
  /** Called when a new token is generated */
  fun onTokenGenerated(tokenArg: TokenData, callback: (Result<Unit>) -> Unit)
{
    val channelName = "dev.flutter.pigeon.executorch_bridge_flutter.ExecutorchFlutterApi.onTokenGenerated"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(tokenArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  /** Called when generation is complete */
  fun onGenerationComplete(fullTextArg: String, totalTokensArg: Long, callback: (Result<Unit>) -> Unit)
{
    val channelName = "dev.flutter.pigeon.executorch_bridge_flutter.ExecutorchFlutterApi.onGenerationComplete"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(fullTextArg, totalTokensArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  /** Called when an error occurs */
  fun onError(errorArg: String, callback: (Result<Unit>) -> Unit)
{
    val channelName = "dev.flutter.pigeon.executorch_bridge_flutter.ExecutorchFlutterApi.onError"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(errorArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
}
